W8D1/reddit_clone/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :subs
  resources :users
  resource :session
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

W8D1/reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W8D1/reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string
#  url        :string
#  content    :string
#  sub_id     :integer
#  author_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :author_id, presence: true

  belongs_to :author, foreign_key: :author_id, class_name: :User

  # belongs_to :sub, foreign_key: :sub_id, class_name: :Sub

  has_many :sub_posts,
    inverse_of: :post

  has_many :subs,
    through: :sub_posts

end

W8D1/reddit_clone/app/models/sub.rb
# == Schema Information;]\
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :moderator_id, presence: true


  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  # has_many :posts, as: :sub

  has_many :sub_posts, dependent: :destroy, inverse_of: :sub

  has_many :posts, through: :sub_posts

end

W8D1/reddit_clone/app/models/sub_post.rb
# == Schema Information
#
# Table name: sub_posts
#
#  id         :bigint           not null, primary key
#  sub_id     :integer
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class SubPost < ApplicationRecord
  # validates :sub_id, :post_id, presence: true
  validates :post_id, uniqueness: {scope: :sub_id}
  
  belongs_to :sub

  belongs_to :post



end

W8D1/reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string
#  password_digest :string
#  session_token   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  attr_reader :password

  has_many :subs, foreign_key: :moderator_id, class_name: :Sub

  has_many :posts, as: :author

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

W8D1/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user

    @current_user ||= User.find_by(session_token: session[:session_token])

  end

  def required_login
    redirect_to new_session_url unless logged_in?

  end

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  
  end


  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end



  def required_login
    redirect_to new_session_url unless logged_in?

  end

  def required_moderator_login

    sub = Sub.find_by(id: params[:id])

    if current_user.id != sub.moderator_id

      flash[:errors] = ["You're not moderator, bro"]
      redirect_to sub_url(sub)
    end

  end





end

W8D1/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :required_login, only: [:new, :create]
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new       
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def show
    @post = Post.find_by(id: params[:id])

  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post && @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else     
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to subs_url
  end

  def post_params
    params.require(:post).permit(:title, :url, :content,  :author_id, sub_ids: [])
  end

end

W8D1/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user 
      login(user)
      redirect_to users_url
    else
      flash[:errors] = ["Wrong username or password"]
      redirect_to new_session_url
    end

  end

  def new
    @user = User.new
  end

  def destroy
    logout
  end
end

W8D1/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :required_login, only: [:new, :create]
  before_action :required_moderator_login, only: [:edit, :update]

  
  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new

    end

  end

  def new
    @sub = Sub.new

  end

  def edit
    @sub = Sub.find_by(id: params[:id])


  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end

    
  end

  def destroy
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find_by(id: params[:id])

  end

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)

  end
end

W8D1/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
    # render :new

  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new

    end

  end

  def destroy
  end

  def show
  end

  def index
  end

  def user_params
    params.require(:user).permit(:username, :password)

  end
end

W8D1/reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

W8D1/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

W8D1/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

W8D1/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= flash[:errors] %>
    <% if logged_in? %>
      <h3>Hello <%= current_user.username %></h3> 
      <form action="<%= session_url %>" method="post"> 
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token"
          value="<%= form_authenticity_token %>"> 
        <button>Sign Out</button>
      </form>
      <button><%= link_to "Create a Sub!", new_sub_url %></button>
      <br>
      <button><%= link_to "All Subs", subs_url %></button>
      
    <% end %>
    <%= yield %>
  </body>
</html>

W8D1/reddit_clone/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

W8D1/reddit_clone/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

W8D1/reddit_clone/app/views/posts/edit.html.erb
<h1>Update Post</h1>
<form action="<%= post_url(params[:id]) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" 
    value="<%= form_authenticity_token %>">
  

  <label>Title
    <input type="text" value="<%= @post.title %>" name="post[title]">
  </label>
  <br>
  <label>URL
    <input type="text" value="<%= @post.url %>" name="post[url]">
  </label>
  <br>
  <label>Content
    <input type="text" value="<%= @post.content %>" name="post[content]">
  </label>
  <br>
  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>"> 

  <label><h1>Subs</h1></label>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input
        type="checkbox"
        value="<%= sub.id %>"
        name="post[sub_ids][]"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>
      />
    </label>

    <br>

  <% end %>

  <input type="submit" value="Edit Post">
</form>

W8D1/reddit_clone/app/views/posts/new.html.erb
<h1>New Post</h1>
<form action="<%= posts_url %>" method="POST">
  <input type="hidden" name="authenticity_token" 
    value="<%= form_authenticity_token %>">
  

  <label>Title
    <input type="text" value="<%= @post.title %>" name="post[title]">
  </label>
  <br>
  <label>URL
    <input type="text" value="<%= @post.url %>" name="post[url]">
  </label>
  <br>
  <label>Content
    <input type="text" value="<%= @post.content %>" name="post[content]">
  </label>
  <br>
  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>"> 

  <label><h1>Subs</h1></label>

  <input type="hidden" name="post[sub_ids][]" value="">

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input
        type="checkbox"
        value="<%= sub.id %>"
        name="post[sub_ids][]"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>
      />
    </label>

    <br>

  <% end %>

  <input type="submit" value="Create Post!">
</form>

W8D1/reddit_clone/app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

<h2><%= @post.title %> by <%= @post.author.username %></h2>
<h4>Content:</h4>
<p><%= @post.content %></p>
<br>

<h4>Subs</h4>
<ul>
  <% @post.subs.each do |sub| %>
    <li>
      <%= sub.title %>
    </li>
  <% end %>
</ul>

<%= link_to "Edit Post", edit_post_url(@post)  %>

<h3>Comments</h3>

W8D1/reddit_clone/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

W8D1/reddit_clone/app/views/shared/_post_form.html.erb
<form action="<%= action_url %>" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <% if http_verb == "patch" %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">

  <label for="">
    Title:
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <br>
  <label for="">
    URL:
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <br>
  <label for="">
    Content:
    <input type="text" name="post[content]" value="<%= post.content %>">
  </label>

  <% Sub.all.each do |sub| %>
    <input type="checkbox" >
  <% end %>


</form>

W8D1/reddit_clone/app/views/shared/_subs_form.html.erb
<form action="<%= action %>" method="post"> 
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> 

  <% if http_verb == "patch" %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <input type="hidden" name="sub[moderator_id]" 
    value="<%= current_user.id %>"> 
  <label for="">Sub-reddit title
    <input type="text" name="sub[title]" value="<%= sub.title %>">
  </label>
  <br>
  <br>

  <label for="">Details 
    <input type="text" name="sub[description]" value="<%= sub.description %>">
  </label>
  <br>
  <button><%= button_text %></button>
  
</form>

W8D1/reddit_clone/app/views/shared/_subs_show.html.erb
<h4> Title: <%= sub.title %> </h4>

<p>
  Description: <%= sub.description %>
</p>


<p> 
  Moderator: <%= User.find_by(id: sub.moderator_id).username %>
</p>

 <%= link_to "Edit This Sub", edit_sub_url(sub) %>

<% if current_user.id == sub.moderator_id %>
 

<% end %>

W8D1/reddit_clone/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

W8D1/reddit_clone/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

W8D1/reddit_clone/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

W8D1/reddit_clone/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= flash[:errors] %>

<h1>Sign Up</h1>

<form action="<%=users_url%>" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="">
      Username
      <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>

   <label for="">
      Password
      <input type="password" name="user[password]" value="<%= @user.password %>">
  </label>

  <button>Sign Up</button>

  

</form>

W8D1/reddit_clone/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>