W7D2/music_app_3/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resource :session, only: [:new, :create, :destroy]

  resource :bands
end

W7D2/music_app_3/app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

    
end

W7D2/music_app_3/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#


class User < ApplicationRecord
    validates :email, presence: true
    validates :password_digest, presence: true

    validates :session_token, presence: true, uniqueness: true
    validates :password, length: { minimum: 6}, allow_nil: true
    after_initialize :ensure_session_token
    attr_reader :password


    def reset_session_token!

        self.update!(session_token: SecureRandom.urlsafe_base64(16))
        self.session_token

    end

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64(16)
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end
      

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        user && user.is_password?(password) ? user : nil

    end



    


end

W7D2/music_app_3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])

    end

    def log_in(user)
        @current_user = user
        # set session token to users session token
        session[:session_token] = user.reset_session_token!

    end

    def logged_in?
        !!current_user
    end

    def logout
        current_user.reset_session_token!

        session[:session_token] = nil
        redirect_to new_session_url
    end


    def require_login

        redirect_to new_session_url unless logged_in?

    end


end

W7D2/music_app_3/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def new
        render :new
    end

    def index
        @bands = Band.all
        render json: @bands
    end

    def show
        @band = Band.find_by(id: params[:id])
        render json: @band

    end

    def create
        band = Band.new(band_params)
        if band.save
            redirect_to band_url(band)
        end
    end


    def band_params

        params.require(:band).permit(:name)
    end

    def destroy
        band = Band.find_by(id: params[:id])
        band.destroy
        render :new

    end
end

W7D2/music_app_3/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new

    end

    def create
        user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )

        if user
            log_in(user)
            redirect_to user_url(user)
        else
            redirect_to new_session_url
        end
    end

    def destroy
        logout
    end
end

W7D2/music_app_3/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        render :new
    end 

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def create

        user = User.new(user_params)

        if user.save
            log_in(user)
            redirect_to user_url(user)
        else
            render json: user.errors.full_messages, status: 418
        end

    end


    def user_params
        params.require(:user).permit(:email, :password)
    end

    


end

W7D2/music_app_3/app/helpers/bands_helper.rb
module BandsHelper
end

W7D2/music_app_3/app/views/bands/new.html.erb
<h1>Enter a new band LoL</h1>

<form action="<%= bands_url %>" method="POST">

    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

    <label> Email:
        <input type="text" name="band[name]">
    </label>
    <br>
    <br>
     <input type="submit">


</form>

W7D2/music_app_3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Coolest Music App Ever</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
    <h1> Welcome to Andy's Music Application </h1>
    <% if logged_in? %>
    <h2> What's up, <%= current_user.email %> </h2>
    <form action="<%=session_url%>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

      <input type="submit" value="Sign out">
    </form>
    <% end %>

    <%= yield %>
  </body>
</html>