W6D5/cats99/config/routes.rb
Rails.application.routes.draw do
  # get 'cats/index'
  # get 'cats/show'
  # get 'cats/new'
  # get 'cats/edit'
  # get 'cats/update'
  # get 'cats/destroy'

  resources :cats

  

end

W6D5/cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  age         :integer          not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string           not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'date'
require 'action_view'

class Cat < ApplicationRecord

  include ActionView::Helpers::DateHelper

  validates :birth_date, :color, :name, :description, :sex, presence: true

  validates :color, inclusion: {in: %w(yellow ginger black radioactive white grey brown pink gold), message: "%{value} is not a valid color" }
  
  validates :sex, inclusion: {in: %w(M F), message: "%{value} is not a valid sex" }

  def age
   
    time_ago_in_words(birth_date)
  
  end


end

W6D5/cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

W6D5/cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController


  def index
    @cats = Cat.all
    render :index

  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
  end
  
  def edit
  end

  def update
  end

  def destroy
  end


  # def cats_params

  # end
end

W6D5/cats99/app/helpers/cats_helper.rb
module CatsHelper
end

W6D5/cats99/app/views/cats/destroy.html.erb
<h1>Cats#destroy</h1>
<p>Find me in app/views/cats/destroy.html.erb</p>

W6D5/cats99/app/views/cats/edit.html.erb
<h1>Cats#edit</h1>
<p>Find me in app/views/cats/edit.html.erb</p>

W6D5/cats99/app/views/cats/index.html.erb
<h1>Welcome to our Cats' page</h1>

<ul>
  <%@cats.each do |cat| %>

  <li>
    <ul> 
      <b><li><%=cat.name%></li></b>
       <li><%=cat.color%></li> 
       <li><%=cat.sex%></li>
       <li><%=cat.birth_date%></li>
       <li><%=cat.age%></li>
       <li><%=cat.description%></li>
       <li><a href="<%=cat_url(cat)%>"> My Profile</a>
    </ul>
  </li>
  <br>

  
  <%end%>
</ul>

W6D5/cats99/app/views/cats/new.html.erb
<h1>Creation of your Cat</h1>

<form action="<%=cats_url%>%" method="POST">
  <label>Name:   <input type="text" name="cat[name]" value=<%=@cat.name%>>

W6D5/cats99/app/views/cats/show.html.erb
<style>

h1 {
  margin:auto;
  text-align: center;
}

body {margin: auto;
  width: 60%;
  <%# border: 3px solid #73AD21; %>
  padding: 10px;
  background-color: pink;

}

table,
td {margin: auto;
    border: 1px solid #333;
}

tr {
  font-size: 20px;
  font: Arial;
}

thead,
tfoot {
    background-color: #333;
    color: #fff;
}

</style>

<h1><%=@cat.name%></h1>
<table style="width:60%">
    <thead>
        <tr>
          <th colspan="2">Name: <%=@cat.name%></th>
        </tr>
    </thead>
    <tbody>
        <tr> 
            <td>Color</td>
            <td><%=@cat.color%></td>
        </tr>
        <tr>
          <td>Sex</td>
          <td><%=@cat.sex%></td>
        </tr>
        <tr>
          <td>Birthdate</td>
          <td><%=@cat.birth_date%></td>
        </tr>
        <tr>
          <td>Description</td>
          <td><%=@cat.description%></td>
        </tr>
    </tbody>
</table>

W6D5/cats99/app/views/cats/update.html.erb
<h1>Cats#update</h1>
<p>Find me in app/views/cats/update.html.erb</p>